#!/usr/bin/env bash
set -euo pipefail

export HYRIBYN=${HYRIBYN:-"$HOME/.local/share/hyribyn/hyribyn"}
export HYRIBYN_ROOT=${HYRIBYN_ROOT:-"$HOME/.local/share/hyribyn/"}

# assign git commits and/or tags to build from source from for each app
# git repos are in "$HOME/.local/share/hyribyn/<appname>"

export RIBYN_HYPR_HYPRUTILS_GITREV=${RIBYN_HYPR_HYPRUTILS_GITREV:-"v0.14.1"}
export RIBYN_HYPR_HYPRWAYLAND_SCANNER_GITREV=${RIBYN_HYPR_HYPRWAYLAND_SCANNER_GITREV:-"v0.4.6"}
export RIBYN_HYPR_AQUAMARINE_GITREV=${RIBYN_HYPR_AQUAMARINE_GITREV:-"v0.14.0"}
export RIBYN_HYPR_HYPRLANG_GITREV=${RIBYN_HYPR_HYPRLANG_GITREV:-"v0.6.8"}
export RIBYN_HYPR_HYPRCURSOR_GITREV=${RIBYN_HYPR_HYPRCURSOR_GITREV:-"v0.1.13"}
export RIBYN_HYPR_HYPRGRAPHICS_GITREV=${RIBYN_HYPR_HYPRGRAPHICS_GITREV:-"v0.5.1"}
export RIBYN_HYPR_HYPRLAND_GITREV=${RIBYN_HYPR_HYPRLAND_GITREV:-"v0.56.0"}
export RIBYN_HYPR_HYPRWIRE_GITREV=${RIBYN_HYPR_HYPRWIRE_GITREV:-"v0.3.1"}
export RIBYN_HYPR_HYPRLAND_GUIUTILS_GITREV=${RIBYN_HYPR_HYPRLAND_GUIUTILS_GITREV:-"v0.2.2"}

# one commit after v0.7.0 they swapped to cmake, so I can reuse my build script :)
export RIBYN_HYPR_HYPRLAND_PROTOCOLS_GITREV=${RIBYN_HYPR_HYPRLAND_PROTOCOLS_GITREV:-"3f3860b869014c00e8b9e0528c7b4ddc335c21ab"}
export RIBYN_HYPR_XDG_DESKTOP_PORTAL_HYPRLAND_GITREV=${RIBYN_HYPR_XDG_DESKTOP_PORTAL_HYPRLAND_GITREV:-"v1.4.1"}

# these are additional apps to hypr, based on hypr. but hypr does not depend on them itself
export RIBYN_HYPR_HYPRTOOLKIT_GITREV=${RIBYN_HYPR_HYPRTOOLKIT_GITREV:-"v0.5.4"}
export RIBYN_HYPR_HYPRPOLKITAGENT_GITREV=${RIBYN_HYPR_HYPRPOLKITAGENT_GITREV:-"v0.1.3"}
export RIBYN_HYPR_HYPRSHUTDOWN_GITREV=${RIBYN_HYPR_HYPRSHUTDOWN_GITREV:-"v0.1.1"}
export RIBYN_HYPR_HYPRPAPER_GITREV=${RIBYN_HYPR_HYPRPAPER_GITREV:-"v0.8.4"}
export RIBYN_HYPR_HYPRLOCK_GITREV=${RIBYN_HYPR_HYPRLOCK_GITREV:-"v0.9.6"}
export RIBYN_HYPR_HYPRPICKER_GITREV=${RIBYN_HYPR_HYPRPICKER_GITREV:-"v0.4.7"}
export RIBYN_HYPR_HYPRMONCFG_GITREV=${RIBYN_HYPR_HYPRMONCFG_GITREV:-"v1.13.0"}

# should match above RIBYN_HYPR_HYPRLAND_GITREV
# for fedora
# but for arch, you pray, or override local env to "origin/master"
# which build againgst the latest untagged hyprland release
# which is similar to pacman updates and unlikely to break
export RIBYN_HYPR_HY3_GITREV=${RIBYN_HYPR_HY3_GITREV:-"hl0.56.0"}
